### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by cvbhsx** [justinludwig/jpgpj#1]
Attempted to build following the README steps but encountered the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/username/Downloads/jpgpj-master 2/build.gradle' line: 89

* What went wrong:
A problem occurred evaluating root project 'jpgpj-master 2'.
> No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 58.094 secs
```

**Comment by cvbhsx** [comment]
Update: I commented out the authentication lines (`authentication userName: ossrhUsername, password: ossrhPassword`) in the build.gradle file and it seemed to build successfully.

**Comment by justinludwig** [comment]
Thanks for pointing out this issue! I removed the extra junk from the main build.gradle file that was there only for my own convenience in uploading releases to maven central, and put it in a separate mavenCentral.gradle file. So now you should be able to run the gradle build without needing to manually fiddle with the build.gradle file.
