### ISSUE TITLE
Decrypt only using Passphrase

### ISSUE THREAD

**Issue by uMANG6891** [justinludwig/jpgpj#2]
I have only used single string passphrase to encrypt the file. How do use this library to decrypt the file?

**Comment by justinludwig** [comment]
You can with a `org.c02e.jpgpj.Decryptor` object, by first setting its `symmetricPassphrase` property to the passphrase and its `verificationRequired` property to false, and then calling its `decrypt()` method. There's an example of this in the Symmetric Decryption section of the Decrypting Files wiki page:

https://github.com/justinludwig/jpgpj/wiki/DecryptingFiles#symmetric-decryption

**Comment by uMANG6891** [comment]
Thanks. It worked.
