### ISSUE TITLE
Buffer size of zero passed to BufferedInputStream in Encryptor.java line 343 results in exception.

### ISSUE THREAD

**Issue by bclark76** [justinludwig/jpgpj#23]
Upgrading from 0.1.1 to 0.7 I got this during testing my code:

java.lang.IllegalArgumentException: Buffer size <= 0
	at java.io.BufferedInputStream.<init>(BufferedInputStream.java:201)
	at org.c02e.jpgpj.Encryptor.encrypt(Encryptor.java:343)

Encryptor.class has: 

            int bestFileBufferSize =
                Util.bestFileBufferSize(plaintext.length(), maxFileBufferSize);
            input = new BufferedInputStream(
                new FileInputStream(plaintext), bestFileBufferSize);

It's passing zero as the buffer size for zero byte plaintexts.

Seems BufferedInputStream has: 

    public BufferedInputStream(InputStream in, int size) {
        super(in);
        if (size <= 0) {
            throw new IllegalArgumentException("Buffer size <= 0"); // this is being thrown
        }
        buf = new byte[size];
    }

Is it possible to pass a buffer size of 1 if the buffer size would be zero?

**Comment by justinludwig** [comment]
Thanks for the bug report! You're right, it should use a buffer size of 1 instead of 0. I'll release a fix for it tonight.

**Comment by justinludwig** [comment]
I fixed this, and released it as version 0.7.1. Thanks again for the detailed bug report!

**Comment by bclark76** [comment]
Wow, that was quick!  Thanks!  Fixed my issue!
