### ISSUE TITLE
Is it possible to use pure java code to make a detached signature ?

### ISSUE THREAD

**Issue by Chen-Dixi** [justinludwig/jpgpj#42]
I want to develop a web service to publish my SDK to maven central repository automatically. It is necessary to create a detached signature during the pipeline wrote in Java. 
What should I do if jpgpj can't create a detached signature?

**Comment by yexiong** [comment]
来信已收到，我会尽快处理。加急请联系：13675888422谢谢叶熊

**Comment by justinludwig** [comment]
You can use the Bouncy Castle library directly to create a detached signature; see this example code:

https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/examples/DetachedSignatureProcessor.java

**Comment by Chen-Dixi** [comment]
Thank you. I'll look into this example.
