### ISSUE TITLE
Replace J-U-L with slf4j

### ISSUE THREAD

**Issue by lgoldstein** [justinludwig/jpgpj#6]
Great library - one minor suggestion - the code uses J-U-L (`java.util.logging`) - _slf4j_ is widely used in most frameworks and seems a more natural choice. If you really want to make this optimal, provide a pluggable logging manager with default implementations for J-U-L, _slf4j_ and _log4j_.

**Comment by justinludwig** [comment]
Thanks for the feedback! -- I merged the PR from @IntelCan to implement this change.
