### ISSUE TITLE
gradlew test BUILD FAILED

### ISSUE THREAD

**Issue by padbits** [justinludwig/jpgpj#9]
EncryptorSpec. encrypt and sign file
EncryptorSpec. encrypt and sign with ascii armor

**Comment by justinludwig** [comment]
Could you run the tests with the `-i` option (ie `./gradlew test -i`), and copy the output of those two tests into a comment for this issue?

**Comment by justinludwig** [comment]
Closing for now -- please re-open if you have more details you want to report.
